# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

import("//brave/build/config.gni")

assert(is_win)

group("omaha") {
  deps = [ ":build_omaha_installer" ]
}

action("build_omaha_installer") {
  script="build_omaha.py"

  inputs = [ "build_omaha.py" ]

  _install_switch = ""
  _tag_app_name = "Herond-Release"
  if (brave_channel == "beta") {
    _install_switch = "--chrome-beta"
    _tag_app_name = "Herond-Browser-Beta"
  } else if (brave_channel == "dev") {
    _install_switch = "--chrome-dev"
    _tag_app_name = "Herond-Browser-Dev"
  } else if (brave_channel == "nightly") {
    _install_switch = "--chrome-sxs"
    _tag_app_name = "Herond-Browser-Nightly"
  } else {
    assert(brave_channel == "", "Unknown channel name")
  }

  # For beta version (x.y.z.t) => The pv should be [chromium_major].x.y.(z*100 + t)
  # Where: x = brave_version_major, y = brave_version_minor, z = brave_version_build, t = herond_version_weekly (or 0 if empty)
  # For non-beta channels, use the standard format
  # Pass channel and version components to Python script for beta version calculation
  if (brave_channel == "beta") {
    _brave_full_version = "$chrome_version_major.$brave_version_major.$brave_version_minor.$brave_version_build.$herond_version_weekly"
  } else {
    _brave_full_version = "$chrome_version_major.$brave_version_major.$brave_version_minor.$brave_version_build"
  }

  out_dir = rebase_path(root_out_dir)

  args = [
    "--root_out_dir=$out_dir",
    "--brave_installer_exe=$brave_installer_exe",
    "--stub_installer_exe=$brave_stub_installer_exe",
    "--stub_untagged_exe=$brave_untagged_stub_installer_exe",
    "--standalone_installer_exe=$brave_standalone_installer_exe",
    "--silent_installer_exe=$brave_silent_installer_exe",
    "--untagged_installer_exe=$brave_untagged_installer_exe",
    "--guid=$brave_app_guid",
    "--install_switch=$_install_switch",
    "--tag_ap=$tag_ap",
    "--tag_app_name=$_tag_app_name",
    "--tag_lang=$tag_lang",
    "--brave_full_version=$_brave_full_version",
  ]

  _tagged_langs = []
  if (tag_lang == "" || tag_lang == "all") {
    _tagged_langs = [
      "en",
      "vi",
    ]
  } else {
    _tagged_langs = string_split(tag_lang, ",")
  }

  outputs = [
    "$root_out_dir/$brave_untagged_installer_exe",
  ]
  foreach(_lang, _tagged_langs) {
    outputs += [
      "$root_out_dir/lang/$_lang/$brave_stub_installer_exe",
      "$root_out_dir/lang/$_lang/$brave_standalone_installer_exe",
      "$root_out_dir/lang/$_lang/$brave_silent_installer_exe",
    ]
  }

  deps = [
    # Transitively depends on //brave/build/win:create_signed_installer.
    # herond_installer.exe must already be signed before it's embedded below.
    "//herond:sign_herond_installer",
  ]
}

